[
  {
    "apartment_id": "apt_001",
    "host": {
      "user_name": "Karim Essam",
      "user_email": "karim.e@example.com",
      "user_phone": "+201001234567",
      "profile_image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=200&q=80",
      "verified": true
    },
    "title": "Modern Studio with Nile View in Zamalek",
    "description": "A chic, modern studio located in the heart of Zamalek with a breathtaking view of the Nile. Perfect for solo travelers or couples.",
    "address": "26th of July Street, Zamalek",
    "city": "Cairo",
    "neighborhood": "Zamalek",
    "latitude": 30.0626,
    "longitude": 31.2229,
    "apartment_type": "Studio",
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "max_guests": 2,
    "amenities": ["WiFi", "AC", "Kitchen", "Elevator", "Washer", "Nile View"],
    "images": [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?fit=crop&w=800&q=80"
    ],
    "price_per_night": 850,
    "currency": "EGP",
    "availability": true,
    "rating": 4.9,
    "reviews_count": 120,
    "rules": "No smoking, No pets",
    "cancellation_policy": "Free cancellation up to 48 hours",
    "check_in_time": "14:00",
    "check_out_time": "11:00"
  },
  {
    "apartment_id": "apt_002",
    "host": {
      "user_name": "Sarah Nabil",
      "user_email": "sarah.n@example.com",
      "profile_image": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?fit=crop&w=200&q=80",
      "verified": true
    },
    "title": "Cozy Bohemian Apartment in Dahab",
    "description": "Relax in this bohemian-style apartment just steps away from the Red Sea. Features a hammock and open roof.",
    "address": "Lighthouse Area, Dahab",
    "city": "Dahab",
    "neighborhood": "Lighthouse",
    "latitude": 28.5096,
    "longitude": 34.5137,
    "apartment_type": "Apartment",
    "bedrooms": 2,
    "beds": 3,
    "bathrooms": 1,
    "max_guests": 4,
    "amenities": ["WiFi", "Kitchen", "Patio", "Beach Access"],
    "images": [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1522771753035-1a5b6562f329?fit=crop&w=800&q=80"
    ],
    "price_per_night": 600,
    "currency": "EGP",
    "availability": true,
    "rating": 4.7,
    "reviews_count": 85,
    "rules": "Pets allowed",
    "cancellation_policy": "Moderate",
    "check_in_time": "13:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_003",
    "host": {
      "user_name": "Ahmed Fathy",
      "user_email": "ahmed.f@example.com",
      "profile_image": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?fit=crop&w=200&q=80",
      "verified": false
    },
    "title": "Luxury Villa with Pool in El Gouna",
    "description": "Exclusive villa in West Golf area with a private heated pool and lagoon view.",
    "address": "West Golf, El Gouna",
    "city": "El Gouna",
    "neighborhood": "West Golf",
    "latitude": 27.3949,
    "longitude": 33.6761,
    "apartment_type": "Villa",
    "bedrooms": 4,
    "beds": 6,
    "bathrooms": 3,
    "max_guests": 8,
    "amenities": ["WiFi", "Pool", "Kitchen", "AC", "Parking", "Lagoon View", "BBQ Grill"],
    "images": [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?fit=crop&w=800&q=80"
    ],
    "price_per_night": 5000,
    "currency": "EGP",
    "availability": true,
    "rating": 5.0,
    "reviews_count": 42,
    "rules": "No parties",
    "cancellation_policy": "Strict",
    "check_in_time": "15:00",
    "check_out_time": "11:00"
  },
  {
    "apartment_id": "apt_004",
    "host": {
      "user_name": "Mona Zaki",
      "user_email": "mona.z@example.com",
      "profile_image": null,
      "verified": true
    },
    "title": "Classic Apartment in Downtown Alexandria",
    "description": "Stay in a historic building with high ceilings and balconies overlooking the Mediterranean Sea.",
    "address": "Saad Zaghloul Square, Alexandria",
    "city": "Alexandria",
    "neighborhood": "Mahatet El Raml",
    "latitude": 31.2001,
    "longitude": 29.9187,
    "apartment_type": "Apartment",
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 2,
    "max_guests": 6,
    "amenities": ["WiFi", "TV", "Washer", "Sea View", "Elevator"],
    "images": [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?fit=crop&w=800&q=80"
    ],
    "price_per_night": 1200,
    "currency": "EGP",
    "availability": false,
    "rating": 4.5,
    "reviews_count": 210,
    "rules": "Quiet hours after 10 PM",
    "cancellation_policy": "Flexible",
    "check_in_time": "14:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_005",
    "host": {
      "user_name": "Omar Sherif",
      "user_email": "omar.sh@example.com",
      "profile_image": "https://images.unsplash.com/photo-1599566150163-29194dcaad36?fit=crop&w=200&q=80",
      "verified": true
    },
    "title": "Eco-Lodge in Siwa Oasis",
    "description": "Experience the desert life in a traditional mud-brick house powered by solar energy.",
    "address": "Shali Fortress area, Siwa",
    "city": "Siwa",
    "neighborhood": "Shali",
    "latitude": 29.2032,
    "longitude": 25.5195,
    "apartment_type": "Chalet",
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 1,
    "max_guests": 2,
    "amenities": ["Breakfast", "Garden", "Fireplace", "No WiFi"],
    "images": [
      "https://images.unsplash.com/photo-1449156493391-d2cfa28e468b?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?fit=crop&w=800&q=80"
    ],
    "price_per_night": 450,
    "currency": "EGP",
    "availability": true,
    "rating": 4.8,
    "reviews_count": 60,
    "rules": "Eco-friendly mindset",
    "cancellation_policy": "Flexible",
    "check_in_time": "12:00",
    "check_out_time": "10:00"
  },
  {
    "apartment_id": "apt_006",
    "host": {
      "user_name": "Laila Ahmed",
      "user_email": "laila.a@example.com",
      "verified": true
    },
    "title": "Spacious Flat in Maadi Degla",
    "description": "Green and quiet neighborhood. Walking distance to CSA and Road 9. Huge terrace.",
    "address": "Road 233, Maadi Degla",
    "city": "Cairo",
    "neighborhood": "Maadi",
    "latitude": 29.9602,
    "longitude": 31.2569,
    "apartment_type": "Apartment",
    "bedrooms": 3,
    "beds": 3,
    "bathrooms": 2,
    "max_guests": 5,
    "amenities": ["WiFi", "AC", "Washer", "Dryer", "Bathtub", "Terrace"],
    "images": [
      "https://images.unsplash.com/photo-1484154218962-a1c002085d2f?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?fit=crop&w=800&q=80"
    ],
    "price_per_night": 1500,
    "currency": "EGP",
    "availability": true,
    "rating": 4.9,
    "reviews_count": 35,
    "cancellation_policy": "Moderate",
    "check_in_time": "15:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_007",
    "host": {
      "user_name": "Hassan Youssef",
      "user_email": "hassan.y@example.com",
      "verified": false
    },
    "title": "Budget Room near Pyramids",
    "description": "Simple clean room with a shared bathroom, but an amazing rooftop view of the Sphinx.",
    "address": "Nazlet El Semman, Giza",
    "city": "Giza",
    "neighborhood": "Pyramids",
    "latitude": 29.9792,
    "longitude": 31.1342,
    "apartment_type": "Private Room",
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 0.5,
    "max_guests": 2,
    "amenities": ["WiFi", "Rooftop Access", "Breakfast"],
    "images": [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?fit=crop&w=800&q=80"
    ],
    "price_per_night": 300,
    "currency": "EGP",
    "availability": true,
    "rating": 4.2,
    "reviews_count": 150,
    "rules": "No alcohol",
    "cancellation_policy": "Flexible",
    "check_in_time": "13:00",
    "check_out_time": "11:00"
  },
  {
    "apartment_id": "apt_008",
    "host": {
      "user_name": "Nour El Din",
      "user_email": "nour@example.com",
      "profile_image": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?fit=crop&w=200&q=80",
      "verified": true
    },
    "title": "Luxury Chalet in North Coast (Sahel)",
    "description": "Direct sea view chalet in Marassi. Access to clubhouse and private beach.",
    "address": "Marassi, North Coast",
    "city": "North Coast",
    "neighborhood": "Sidi Abdel Rahman",
    "latitude": 30.9833,
    "longitude": 28.8333,
    "apartment_type": "Chalet",
    "bedrooms": 3,
    "beds": 5,
    "bathrooms": 2,
    "max_guests": 6,
    "amenities": ["Pool", "Beach Access", "AC", "Kitchen", "Parking"],
    "images": [
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?fit=crop&w=800&q=80"
    ],
    "price_per_night": 7000,
    "currency": "EGP",
    "availability": true,
    "rating": 4.6,
    "reviews_count": 20,
    "rules": "Families only",
    "cancellation_policy": "Strict",
    "check_in_time": "15:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_009",
    "host": {
      "user_name": "Rania Kamal",
      "user_email": "rania@example.com",
      "verified": true
    },
    "title": "Nubian House West Bank Luxor",
    "description": "Colorful traditional house on the west bank of the Nile. Quiet and authentic.",
    "address": "Ramla Street, West Bank",
    "city": "Luxor",
    "neighborhood": "West Bank",
    "latitude": 25.6872,
    "longitude": 32.6296,
    "apartment_type": "House",
    "bedrooms": 2,
    "beds": 4,
    "bathrooms": 1,
    "max_guests": 4,
    "amenities": ["Garden", "Breakfast", "Bicycle Rental", "WiFi"],
    "images": [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?fit=crop&w=800&q=80"
    ],
    "price_per_night": 550,
    "currency": "EGP",
    "availability": true,
    "rating": 4.9,
    "reviews_count": 95,
    "cancellation_policy": "Moderate",
    "check_in_time": "14:00",
    "check_out_time": "11:00"
  },
  {
    "apartment_id": "apt_010",
    "host": {
      "user_name": "Tarek Ali",
      "user_email": "tarek@example.com",
      "verified": true
    },
    "title": "Smart Apartment in New Cairo",
    "description": "Fully automated smart home near AUC. High-speed internet and workspace available.",
    "address": "Fifth Settlement, New Cairo",
    "city": "Cairo",
    "neighborhood": "Fifth Settlement",
    "latitude": 30.0074,
    "longitude": 31.4913,
    "apartment_type": "Apartment",
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 2,
    "max_guests": 4,
    "amenities": ["Smart Lock", "WiFi", "Work Desk", "Gym Access", "Pool"],
    "images": [
      "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?fit=crop&w=800&q=80"
    ],
    "price_per_night": 2200,
    "currency": "EGP",
    "availability": true,
    "rating": 4.8,
    "reviews_count": 45,
    "cancellation_policy": "Flexible",
    "check_in_time": "15:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_011",
    "host": {
      "user_name": "Dina Magdy",
      "user_email": "dina@example.com",
      "verified": false
    },
    "title": "Sea View Apartment in Port Said",
    "description": "Enjoy the ship passing through the Suez Canal from your balcony.",
    "address": "El Gomhouria St, Port Said",
    "city": "Port Said",
    "neighborhood": "Port Fouad",
    "latitude": 31.2653,
    "longitude": 32.3019,
    "apartment_type": "Apartment",
    "bedrooms": 2,
    "beds": 3,
    "bathrooms": 1,
    "max_guests": 5,
    "amenities": ["Balcony", "TV", "Kitchen", "Elevator"],
    "images": [
      "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502005229766-3a6dcfd16d6c?fit=crop&w=800&q=80"
    ],
    "price_per_night": 750,
    "currency": "EGP",
    "availability": true,
    "rating": 4.4,
    "reviews_count": 30,
    "cancellation_policy": "Moderate",
    "check_in_time": "14:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_012",
    "host": {
      "user_name": "Yasser Gamal",
      "user_email": "yasser@example.com",
      "verified": true
    },
    "title": "Farmhouse in Fayoum Tunis Village",
    "description": "Escape the city to this artistic farmhouse. Pottery workshops nearby.",
    "address": "Tunis Village, Fayoum",
    "city": "Fayoum",
    "neighborhood": "Tunis Village",
    "latitude": 29.4093,
    "longitude": 30.7360,
    "apartment_type": "Farm Stay",
    "bedrooms": 3,
    "beds": 5,
    "bathrooms": 2,
    "max_guests": 7,
    "amenities": ["Garden", "Fire Pit", "Pottery Studio", "Breakfast"],
    "images": [
      "https://images.unsplash.com/photo-1500076656116-558758c991c1?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1469796466635-5a4adb731da6?fit=crop&w=800&q=80"
    ],
    "price_per_night": 1100,
    "currency": "EGP",
    "availability": true,
    "rating": 4.9,
    "reviews_count": 88,
    "rules": "Pets allowed",
    "cancellation_policy": "Flexible",
    "check_in_time": "14:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_013",
    "host": {
      "user_name": "Salma Hayek",
      "user_email": "salma@example.com",
      "verified": true
    },
    "title": "Minimalist Loft in Heliopolis",
    "description": "High ceilings, industrial design, located near Korba heritage buildings.",
    "address": "Baghdad St, Heliopolis",
    "city": "Cairo",
    "neighborhood": "Heliopolis",
    "latitude": 30.0898,
    "longitude": 31.3283,
    "apartment_type": "Loft",
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "max_guests": 2,
    "amenities": ["WiFi", "AC", "Espresso Machine", "Workspace"],
    "images": [
      "https://images.unsplash.com/photo-1505693416388-b0346ef4143d?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1534349762913-5b4c6299dd8e?fit=crop&w=800&q=80"
    ],
    "price_per_night": 950,
    "currency": "EGP",
    "availability": true,
    "rating": 4.7,
    "reviews_count": 55,
    "cancellation_policy": "Strict",
    "check_in_time": "15:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_014",
    "host": {
      "user_name": "Khaled Saeed",
      "user_email": "khaled@example.com",
      "verified": false
    },
    "title": "Camping Spot in Ras Shitan",
    "description": "Simple hut directly on the beach. Perfect for stargazing and relaxation.",
    "address": "Nuweiba-Taba Road",
    "city": "Nuweiba",
    "neighborhood": "Ras Shitan",
    "latitude": 29.1352,
    "longitude": 34.6653,
    "apartment_type": "Hut",
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 0,
    "max_guests": 2,
    "amenities": ["Beach", "Campfire", "Shared Bathroom"],
    "images": [
      "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?fit=crop&w=800&q=80"
    ],
    "price_per_night": 200,
    "currency": "EGP",
    "availability": true,
    "rating": 4.5,
    "reviews_count": 112,
    "rules": "Bring your own sleeping bag",
    "cancellation_policy": "Flexible",
    "check_in_time": "12:00",
    "check_out_time": "12:00"
  },
  {
    "apartment_id": "apt_015",
    "host": {
      "user_name": "Amina Khalil",
      "user_email": "amina@example.com",
      "verified": true
    },
    "title": "Duplex in Sheikh Zayed",
    "description": "Modern duplex with a small garden in a secure compound.",
    "address": "Beverly Hills, Sheikh Zayed",
    "city": "Giza",
    "neighborhood": "Sheikh Zayed",
    "latitude": 30.0538,
    "longitude": 30.9678,
    "apartment_type": "Duplex",
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 3,
    "max_guests": 6,
    "amenities": ["WiFi", "Garden", "Pool Access", "Security"],
    "images": [
      "https://images.unsplash.com/photo-1515263487990-61b07816b324?fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1484154218962-a1c002085d2f?fit=crop&w=800&q=80"
    ],
    "price_per_night": 2500,
    "currency": "EGP",
    "availability": false,
    "rating": 4.8,
    "reviews_count": 25,
    "cancellation_policy": "Moderate",
    "check_in_time": "14:00",
    "check_out_time": "11:00"
  }
]